# This file will drive the integration testing process for the project

version: '2'
services:
    rabbitmq:
        image: rabbitmq:management
        expose:
        - "5672"
        - "15672"
        # limit RabbitMQ to 1GB of RAM or it will steal 40% of available memory
        mem_limit: 1000000000
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
            RABBITMQ_DEFAULT_VHOST: /
    gradle-cache:
        image: busybox
        network_mode: "none"
        command: "true"
        volumes:
        - /gradle-cache
        - /fake-home
    all-in-one-step:
#       image: kurron/docker-docker-compose:1.7.0
        image: kurron/docker-oracle-jdk-8:1.8.0_101
        depends_on:
        - rabbitmq
        links:
        - rabbitmq:rabbitmq
        stdin_open: true
        tty: true
        working_dir: /code
        volumes_from:
        - gradle-cache
        volumes:
        - /home/vagrant/GitHub/lazybones-experiment/templates/jvm-guy-spring-boot-project:/code:ro
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - JVM_HEAP_MAX=128m
        - SPRING_RABBITMQ_HOST=rabbitmq
        - LANG=en_US.UTF-8
        - LANGUAGE=en_US
        - HOME=/fake-home
        - COMPOSE_HTTP_TIMEOUT=90
        - COMPOSE_PROJECT_NAME=build-test
        privileged: false
        hostname: testing
        domainname: example.com
        command: ./gradlew  --project-prop runIntegrationTests=true --project-prop publishArtifacts=true --project-prop branch=master --project-prop buildDir=/fake-home/build --project-dir=/code --console=plain --no-daemon --no-search-upward --gradle-user-home=/fake-home --project-cache-dir=/gradle-cache --stacktrace
