# Intended to build and run the container during the acceptance testing phase
version: '2'
services:
    rabbitmq:
        image: rabbitmq:management
        expose:
        - "5672"
        - "15672"
        # limit RabbitMQ to 1GB of RAM or it will steal 40% of available memory
        mem_limit: 1000000000
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
            RABBITMQ_DEFAULT_VHOST: /

    ${projectName}:
        build: .
        depends_on:
        - rabbitmq
        links:
        - rabbitmq:rabbitmq
        labels:
            org.kurron.service: "${projectName}"
            org.kurron.built-on: "${generated}"
            org.kurron.branch: "${branch}"
            org.kurron.version: "${version}"
        ports:
        - "8080"
        environment:
            JVM_HEAP_MAX: 128m
            JVM_JMX_HOST: 127.0.0.1
            JVM_JMX_PORT: 2020
            SPRING_RABBITMQ_HOST: rabbitmq
        cpu_shares: 0
        cpu_quota: 0
        mem_limit: 256m
        memswap_limit: 256m
